[package]
name = "lcov2xml"
version = "1.0.0"
edition = "2021"
license-file = "LICENSE"
description = "convert LCOV info file to cobertura XML format"
repository = "https://github.com/mike-kfed/lcov2cobertura"
keywords = ["coverage", "gitlab", "cobertura", "lcov"]
categories = ["command-line-utilities"]

[workspace]

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0", features = ["derive"]}
lcov = "0.8.1"
lcov2cobertura = { path = "lcov2cobertura" }
