[package]
name = "lcov2xml"
version = "1.0.0"
edition = "2021"

[workspace]

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0", features = ["derive"]}
lcov = "0.8.1"
lcov2cobertura = { path = "lcov2cobertura" }
