name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  FUTURE_INCOMPATIBLE: "-F ambiguous-associated-items -F cenum-impl-drop-cast -F coherence-leak-check -F conflicting-repr-hints -F const-err -F const-evaluatable-unchecked -F deprecated-cfg-attr-crate-type-name -F deref-into-dyn-supertrait -A forbidden-lint-groups -F ill-formed-attribute-input -F illegal-floating-point-literal-pattern -F indirect-structural-match -F invalid-doc-attributes -F invalid-type-param-default -F late-bound-lifetime-arguments -F legacy-derive-helpers -F macro-expanded-macro-exports-accessed-by-absolute-paths -F missing-fragment-specifier -F nontrivial-structural-match -F order-dependent-trait-objects -F patterns-in-fns-without-body -F pointer-structural-match -F private-in-public -F proc-macro-back-compat -F proc-macro-derive-resolution-fallback -F pub-use-of-private-extern-crate -F semicolon-in-expressions-from-macros -F soft-unstable -F unaligned-references -F uninhabited-static -F unstable-name-collisions -F unsupported-calling-conventions -F where-clauses-object-safety"
  RUSTFLAGS: "-D warnings -D missing_docs -F rust-2021-compatibility -D rust-2018-idioms -D nonstandard-style"
  CLIPPY_FLAGS: "-F clippy::suspicious -F clippy::style -F clippy::complexity -F clippy::perf"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: formatting
      #echo 'RUSTFLAGS="${{env.RUSTFLAGS}} ${{env.FUTURE_INCOMPATIBLE}}"' >> $GITHUB_ENV
      run: |
        echo 'RUSTFLAGS="${{env.RUSTFLAGS}} ${{env.FUTURE_INCOMPATIBLE}}"'
        cargo fmt --all -- --check
    - name: quality
      run: cargo clippy --workspace --bins --examples --tests --no-deps -- $CLIPPY_FLAGS
    - name: Build
      run: cargo check --workspace --bins --examples --tests
    - name: Run tests
      run: cargo test --release --workspace
