name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: formatting
      run: cargo fmt --all -- --check
    - name: quality
      run: cargo clippy --workspace --bins --examples --tests --no-deps
    - name: Build
      run: cargo check --workspace --bins --examples --tests
    - name: Run tests
      run: cargo test --release --workspace
